// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: send.proto

package com.lyncc.netty.codec.protobuf.demo;

public final class sendProto {
  private sendProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface sendOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netty.send)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>optional uint32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>optional uint32 packageType = 2;</code>
     */
    boolean hasPackageType();
    /**
     * <code>optional uint32 packageType = 2;</code>
     */
    int getPackageType();

    /**
     * <code>optional uint32 chain = 3;</code>
     */
    boolean hasChain();
    /**
     * <code>optional uint32 chain = 3;</code>
     */
    int getChain();

    /**
     * <code>optional uint32 __padding = 4;</code>
     */
    boolean hasPadding();
    /**
     * <code>optional uint32 __padding = 4;</code>
     */
    int getPadding();

    /**
     * <code>optional int32 topicID = 5;</code>
     */
    boolean hasTopicID();
    /**
     * <code>optional int32 topicID = 5;</code>
     */
    int getTopicID();

    /**
     * <code>optional int32 tID = 6;</code>
     */
    boolean hasTID();
    /**
     * <code>optional int32 tID = 6;</code>
     */
    int getTID();

    /**
     * <code>optional int32 requestID = 7;</code>
     */
    boolean hasRequestID();
    /**
     * <code>optional int32 requestID = 7;</code>
     */
    int getRequestID();

    /**
     * <code>optional int32 bodyLen = 8;</code>
     */
    boolean hasBodyLen();
    /**
     * <code>optional int32 bodyLen = 8;</code>
     */
    int getBodyLen();

    /**
     * <code>optional int32 fieldCount = 9;</code>
     */
    boolean hasFieldCount();
    /**
     * <code>optional int32 fieldCount = 9;</code>
     */
    int getFieldCount();

    /**
     * <code>optional int64 sequenceNo = 10;</code>
     */
    boolean hasSequenceNo();
    /**
     * <code>optional int64 sequenceNo = 10;</code>
     */
    long getSequenceNo();

    /**
     * <code>optional int64 lastSn = 11;</code>
     */
    boolean hasLastSn();
    /**
     * <code>optional int64 lastSn = 11;</code>
     */
    long getLastSn();

    /**
     * <code>optional int32 fieldID = 12;</code>
     */
    boolean hasFieldID();
    /**
     * <code>optional int32 fieldID = 12;</code>
     */
    int getFieldID();

    /**
     * <code>optional int32 fieldLenth = 13;</code>
     */
    boolean hasFieldLenth();
    /**
     * <code>optional int32 fieldLenth = 13;</code>
     */
    int getFieldLenth();
  }
  /**
   * Protobuf type {@code netty.send}
   */
  public static final class send extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:netty.send)
      sendOrBuilder {
    // Use send.newBuilder() to construct.
    private send(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private send(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final send defaultInstance;
    public static send getDefaultInstance() {
      return defaultInstance;
    }

    public send getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private send(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              packageType_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              chain_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              Padding_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              topicID_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              tID_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              requestID_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              bodyLen_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              fieldCount_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              sequenceNo_ = input.readInt64();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              lastSn_ = input.readInt64();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              fieldID_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              fieldLenth_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lyncc.netty.codec.protobuf.demo.sendProto.internal_static_netty_send_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lyncc.netty.codec.protobuf.demo.sendProto.internal_static_netty_send_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lyncc.netty.codec.protobuf.demo.sendProto.send.class, com.lyncc.netty.codec.protobuf.demo.sendProto.send.Builder.class);
    }

    public static com.google.protobuf.Parser<send> PARSER =
        new com.google.protobuf.AbstractParser<send>() {
      public send parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new send(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<send> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>optional uint32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int PACKAGETYPE_FIELD_NUMBER = 2;
    private int packageType_;
    /**
     * <code>optional uint32 packageType = 2;</code>
     */
    public boolean hasPackageType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 packageType = 2;</code>
     */
    public int getPackageType() {
      return packageType_;
    }

    public static final int CHAIN_FIELD_NUMBER = 3;
    private int chain_;
    /**
     * <code>optional uint32 chain = 3;</code>
     */
    public boolean hasChain() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 chain = 3;</code>
     */
    public int getChain() {
      return chain_;
    }

    public static final int __PADDING_FIELD_NUMBER = 4;
    private int Padding_;
    /**
     * <code>optional uint32 __padding = 4;</code>
     */
    public boolean hasPadding() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 __padding = 4;</code>
     */
    public int getPadding() {
      return Padding_;
    }

    public static final int TOPICID_FIELD_NUMBER = 5;
    private int topicID_;
    /**
     * <code>optional int32 topicID = 5;</code>
     */
    public boolean hasTopicID() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 topicID = 5;</code>
     */
    public int getTopicID() {
      return topicID_;
    }

    public static final int TID_FIELD_NUMBER = 6;
    private int tID_;
    /**
     * <code>optional int32 tID = 6;</code>
     */
    public boolean hasTID() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 tID = 6;</code>
     */
    public int getTID() {
      return tID_;
    }

    public static final int REQUESTID_FIELD_NUMBER = 7;
    private int requestID_;
    /**
     * <code>optional int32 requestID = 7;</code>
     */
    public boolean hasRequestID() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 requestID = 7;</code>
     */
    public int getRequestID() {
      return requestID_;
    }

    public static final int BODYLEN_FIELD_NUMBER = 8;
    private int bodyLen_;
    /**
     * <code>optional int32 bodyLen = 8;</code>
     */
    public boolean hasBodyLen() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 bodyLen = 8;</code>
     */
    public int getBodyLen() {
      return bodyLen_;
    }

    public static final int FIELDCOUNT_FIELD_NUMBER = 9;
    private int fieldCount_;
    /**
     * <code>optional int32 fieldCount = 9;</code>
     */
    public boolean hasFieldCount() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 fieldCount = 9;</code>
     */
    public int getFieldCount() {
      return fieldCount_;
    }

    public static final int SEQUENCENO_FIELD_NUMBER = 10;
    private long sequenceNo_;
    /**
     * <code>optional int64 sequenceNo = 10;</code>
     */
    public boolean hasSequenceNo() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int64 sequenceNo = 10;</code>
     */
    public long getSequenceNo() {
      return sequenceNo_;
    }

    public static final int LASTSN_FIELD_NUMBER = 11;
    private long lastSn_;
    /**
     * <code>optional int64 lastSn = 11;</code>
     */
    public boolean hasLastSn() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int64 lastSn = 11;</code>
     */
    public long getLastSn() {
      return lastSn_;
    }

    public static final int FIELDID_FIELD_NUMBER = 12;
    private int fieldID_;
    /**
     * <code>optional int32 fieldID = 12;</code>
     */
    public boolean hasFieldID() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int32 fieldID = 12;</code>
     */
    public int getFieldID() {
      return fieldID_;
    }

    public static final int FIELDLENTH_FIELD_NUMBER = 13;
    private int fieldLenth_;
    /**
     * <code>optional int32 fieldLenth = 13;</code>
     */
    public boolean hasFieldLenth() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional int32 fieldLenth = 13;</code>
     */
    public int getFieldLenth() {
      return fieldLenth_;
    }

    private void initFields() {
      version_ = 0;
      packageType_ = 0;
      chain_ = 0;
      Padding_ = 0;
      topicID_ = 0;
      tID_ = 0;
      requestID_ = 0;
      bodyLen_ = 0;
      fieldCount_ = 0;
      sequenceNo_ = 0L;
      lastSn_ = 0L;
      fieldID_ = 0;
      fieldLenth_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, packageType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, chain_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, Padding_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, topicID_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, tID_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, requestID_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, bodyLen_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, fieldCount_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt64(10, sequenceNo_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt64(11, lastSn_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, fieldID_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, fieldLenth_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, packageType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, chain_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, Padding_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, topicID_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, tID_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, requestID_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, bodyLen_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, fieldCount_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, sequenceNo_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, lastSn_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, fieldID_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, fieldLenth_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lyncc.netty.codec.protobuf.demo.sendProto.send parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lyncc.netty.codec.protobuf.demo.sendProto.send parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lyncc.netty.codec.protobuf.demo.sendProto.send parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lyncc.netty.codec.protobuf.demo.sendProto.send parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lyncc.netty.codec.protobuf.demo.sendProto.send parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lyncc.netty.codec.protobuf.demo.sendProto.send parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lyncc.netty.codec.protobuf.demo.sendProto.send parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lyncc.netty.codec.protobuf.demo.sendProto.send parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lyncc.netty.codec.protobuf.demo.sendProto.send parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lyncc.netty.codec.protobuf.demo.sendProto.send parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lyncc.netty.codec.protobuf.demo.sendProto.send prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.send}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netty.send)
        com.lyncc.netty.codec.protobuf.demo.sendProto.sendOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lyncc.netty.codec.protobuf.demo.sendProto.internal_static_netty_send_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lyncc.netty.codec.protobuf.demo.sendProto.internal_static_netty_send_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lyncc.netty.codec.protobuf.demo.sendProto.send.class, com.lyncc.netty.codec.protobuf.demo.sendProto.send.Builder.class);
      }

      // Construct using com.lyncc.netty.codec.protobuf.demo.sendProto.send.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        packageType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        chain_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        Padding_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        topicID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        tID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        requestID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        bodyLen_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        fieldCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        sequenceNo_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        lastSn_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        fieldID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        fieldLenth_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lyncc.netty.codec.protobuf.demo.sendProto.internal_static_netty_send_descriptor;
      }

      public com.lyncc.netty.codec.protobuf.demo.sendProto.send getDefaultInstanceForType() {
        return com.lyncc.netty.codec.protobuf.demo.sendProto.send.getDefaultInstance();
      }

      public com.lyncc.netty.codec.protobuf.demo.sendProto.send build() {
        com.lyncc.netty.codec.protobuf.demo.sendProto.send result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lyncc.netty.codec.protobuf.demo.sendProto.send buildPartial() {
        com.lyncc.netty.codec.protobuf.demo.sendProto.send result = new com.lyncc.netty.codec.protobuf.demo.sendProto.send(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.packageType_ = packageType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.chain_ = chain_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.Padding_ = Padding_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.topicID_ = topicID_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.tID_ = tID_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.requestID_ = requestID_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.bodyLen_ = bodyLen_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.fieldCount_ = fieldCount_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.sequenceNo_ = sequenceNo_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.lastSn_ = lastSn_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.fieldID_ = fieldID_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.fieldLenth_ = fieldLenth_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lyncc.netty.codec.protobuf.demo.sendProto.send) {
          return mergeFrom((com.lyncc.netty.codec.protobuf.demo.sendProto.send)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lyncc.netty.codec.protobuf.demo.sendProto.send other) {
        if (other == com.lyncc.netty.codec.protobuf.demo.sendProto.send.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasPackageType()) {
          setPackageType(other.getPackageType());
        }
        if (other.hasChain()) {
          setChain(other.getChain());
        }
        if (other.hasPadding()) {
          setPadding(other.getPadding());
        }
        if (other.hasTopicID()) {
          setTopicID(other.getTopicID());
        }
        if (other.hasTID()) {
          setTID(other.getTID());
        }
        if (other.hasRequestID()) {
          setRequestID(other.getRequestID());
        }
        if (other.hasBodyLen()) {
          setBodyLen(other.getBodyLen());
        }
        if (other.hasFieldCount()) {
          setFieldCount(other.getFieldCount());
        }
        if (other.hasSequenceNo()) {
          setSequenceNo(other.getSequenceNo());
        }
        if (other.hasLastSn()) {
          setLastSn(other.getLastSn());
        }
        if (other.hasFieldID()) {
          setFieldID(other.getFieldID());
        }
        if (other.hasFieldLenth()) {
          setFieldLenth(other.getFieldLenth());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lyncc.netty.codec.protobuf.demo.sendProto.send parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lyncc.netty.codec.protobuf.demo.sendProto.send) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <code>optional uint32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional uint32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private int packageType_ ;
      /**
       * <code>optional uint32 packageType = 2;</code>
       */
      public boolean hasPackageType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 packageType = 2;</code>
       */
      public int getPackageType() {
        return packageType_;
      }
      /**
       * <code>optional uint32 packageType = 2;</code>
       */
      public Builder setPackageType(int value) {
        bitField0_ |= 0x00000002;
        packageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 packageType = 2;</code>
       */
      public Builder clearPackageType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        packageType_ = 0;
        onChanged();
        return this;
      }

      private int chain_ ;
      /**
       * <code>optional uint32 chain = 3;</code>
       */
      public boolean hasChain() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 chain = 3;</code>
       */
      public int getChain() {
        return chain_;
      }
      /**
       * <code>optional uint32 chain = 3;</code>
       */
      public Builder setChain(int value) {
        bitField0_ |= 0x00000004;
        chain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 chain = 3;</code>
       */
      public Builder clearChain() {
        bitField0_ = (bitField0_ & ~0x00000004);
        chain_ = 0;
        onChanged();
        return this;
      }

      private int Padding_ ;
      /**
       * <code>optional uint32 __padding = 4;</code>
       */
      public boolean hasPadding() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 __padding = 4;</code>
       */
      public int getPadding() {
        return Padding_;
      }
      /**
       * <code>optional uint32 __padding = 4;</code>
       */
      public Builder setPadding(int value) {
        bitField0_ |= 0x00000008;
        Padding_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 __padding = 4;</code>
       */
      public Builder clearPadding() {
        bitField0_ = (bitField0_ & ~0x00000008);
        Padding_ = 0;
        onChanged();
        return this;
      }

      private int topicID_ ;
      /**
       * <code>optional int32 topicID = 5;</code>
       */
      public boolean hasTopicID() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 topicID = 5;</code>
       */
      public int getTopicID() {
        return topicID_;
      }
      /**
       * <code>optional int32 topicID = 5;</code>
       */
      public Builder setTopicID(int value) {
        bitField0_ |= 0x00000010;
        topicID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 topicID = 5;</code>
       */
      public Builder clearTopicID() {
        bitField0_ = (bitField0_ & ~0x00000010);
        topicID_ = 0;
        onChanged();
        return this;
      }

      private int tID_ ;
      /**
       * <code>optional int32 tID = 6;</code>
       */
      public boolean hasTID() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 tID = 6;</code>
       */
      public int getTID() {
        return tID_;
      }
      /**
       * <code>optional int32 tID = 6;</code>
       */
      public Builder setTID(int value) {
        bitField0_ |= 0x00000020;
        tID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 tID = 6;</code>
       */
      public Builder clearTID() {
        bitField0_ = (bitField0_ & ~0x00000020);
        tID_ = 0;
        onChanged();
        return this;
      }

      private int requestID_ ;
      /**
       * <code>optional int32 requestID = 7;</code>
       */
      public boolean hasRequestID() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 requestID = 7;</code>
       */
      public int getRequestID() {
        return requestID_;
      }
      /**
       * <code>optional int32 requestID = 7;</code>
       */
      public Builder setRequestID(int value) {
        bitField0_ |= 0x00000040;
        requestID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 requestID = 7;</code>
       */
      public Builder clearRequestID() {
        bitField0_ = (bitField0_ & ~0x00000040);
        requestID_ = 0;
        onChanged();
        return this;
      }

      private int bodyLen_ ;
      /**
       * <code>optional int32 bodyLen = 8;</code>
       */
      public boolean hasBodyLen() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 bodyLen = 8;</code>
       */
      public int getBodyLen() {
        return bodyLen_;
      }
      /**
       * <code>optional int32 bodyLen = 8;</code>
       */
      public Builder setBodyLen(int value) {
        bitField0_ |= 0x00000080;
        bodyLen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bodyLen = 8;</code>
       */
      public Builder clearBodyLen() {
        bitField0_ = (bitField0_ & ~0x00000080);
        bodyLen_ = 0;
        onChanged();
        return this;
      }

      private int fieldCount_ ;
      /**
       * <code>optional int32 fieldCount = 9;</code>
       */
      public boolean hasFieldCount() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 fieldCount = 9;</code>
       */
      public int getFieldCount() {
        return fieldCount_;
      }
      /**
       * <code>optional int32 fieldCount = 9;</code>
       */
      public Builder setFieldCount(int value) {
        bitField0_ |= 0x00000100;
        fieldCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 fieldCount = 9;</code>
       */
      public Builder clearFieldCount() {
        bitField0_ = (bitField0_ & ~0x00000100);
        fieldCount_ = 0;
        onChanged();
        return this;
      }

      private long sequenceNo_ ;
      /**
       * <code>optional int64 sequenceNo = 10;</code>
       */
      public boolean hasSequenceNo() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int64 sequenceNo = 10;</code>
       */
      public long getSequenceNo() {
        return sequenceNo_;
      }
      /**
       * <code>optional int64 sequenceNo = 10;</code>
       */
      public Builder setSequenceNo(long value) {
        bitField0_ |= 0x00000200;
        sequenceNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sequenceNo = 10;</code>
       */
      public Builder clearSequenceNo() {
        bitField0_ = (bitField0_ & ~0x00000200);
        sequenceNo_ = 0L;
        onChanged();
        return this;
      }

      private long lastSn_ ;
      /**
       * <code>optional int64 lastSn = 11;</code>
       */
      public boolean hasLastSn() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int64 lastSn = 11;</code>
       */
      public long getLastSn() {
        return lastSn_;
      }
      /**
       * <code>optional int64 lastSn = 11;</code>
       */
      public Builder setLastSn(long value) {
        bitField0_ |= 0x00000400;
        lastSn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 lastSn = 11;</code>
       */
      public Builder clearLastSn() {
        bitField0_ = (bitField0_ & ~0x00000400);
        lastSn_ = 0L;
        onChanged();
        return this;
      }

      private int fieldID_ ;
      /**
       * <code>optional int32 fieldID = 12;</code>
       */
      public boolean hasFieldID() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int32 fieldID = 12;</code>
       */
      public int getFieldID() {
        return fieldID_;
      }
      /**
       * <code>optional int32 fieldID = 12;</code>
       */
      public Builder setFieldID(int value) {
        bitField0_ |= 0x00000800;
        fieldID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 fieldID = 12;</code>
       */
      public Builder clearFieldID() {
        bitField0_ = (bitField0_ & ~0x00000800);
        fieldID_ = 0;
        onChanged();
        return this;
      }

      private int fieldLenth_ ;
      /**
       * <code>optional int32 fieldLenth = 13;</code>
       */
      public boolean hasFieldLenth() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional int32 fieldLenth = 13;</code>
       */
      public int getFieldLenth() {
        return fieldLenth_;
      }
      /**
       * <code>optional int32 fieldLenth = 13;</code>
       */
      public Builder setFieldLenth(int value) {
        bitField0_ |= 0x00001000;
        fieldLenth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 fieldLenth = 13;</code>
       */
      public Builder clearFieldLenth() {
        bitField0_ = (bitField0_ & ~0x00001000);
        fieldLenth_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:netty.send)
    }

    static {
      defaultInstance = new send(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:netty.send)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_send_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netty_send_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nsend.proto\022\005netty\"\355\001\n\004send\022\017\n\007version\030" +
      "\001 \001(\r\022\023\n\013packageType\030\002 \001(\r\022\r\n\005chain\030\003 \001(" +
      "\r\022\021\n\t__padding\030\004 \001(\r\022\017\n\007topicID\030\005 \001(\005\022\013\n" +
      "\003tID\030\006 \001(\005\022\021\n\trequestID\030\007 \001(\005\022\017\n\007bodyLen" +
      "\030\010 \001(\005\022\022\n\nfieldCount\030\t \001(\005\022\022\n\nsequenceNo" +
      "\030\n \001(\003\022\016\n\006lastSn\030\013 \001(\003\022\017\n\007fieldID\030\014 \001(\005\022" +
      "\022\n\nfieldLenth\030\r \001(\005B0\n#com.lyncc.netty.c" +
      "odec.protobuf.demoB\tsendProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_netty_send_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netty_send_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_netty_send_descriptor,
        new java.lang.String[] { "Version", "PackageType", "Chain", "Padding", "TopicID", "TID", "RequestID", "BodyLen", "FieldCount", "SequenceNo", "LastSn", "FieldID", "FieldLenth", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
